# Generated by Django 3.0.8 on 2020-12-29 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='trasactions',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=200, unique=True)),
                ('nodes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nodes')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trasactions')),
            ],
        ),
        migrations.AddField(
            model_name='trasactions',
            name='nodes',
            field=models.ManyToManyField(through='api.solutions', to='api.nodes'),
        ),
    ]
