# Generated by Django 3.0.8 on 2021-05-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201229_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=200, unique=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inputs')),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_tag', models.CharField(max_length=200, unique=True)),
                ('inputs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inputs')),
                ('outputs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.outputs')),
            ],
        ),
        migrations.RemoveField(
            model_name='trasactions',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='trasactions',
            name='users',
        ),
        migrations.AddField(
            model_name='nodes',
            name='type',
            field=models.CharField(default='IOTA node', max_length=200),
        ),
        migrations.DeleteModel(
            name='solutions',
        ),
        migrations.DeleteModel(
            name='trasactions',
        ),
        migrations.AddField(
            model_name='problem',
            name='proccessor',
            field=models.ManyToManyField(to='api.nodes'),
        ),
        migrations.AddField(
            model_name='outputs',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nodes'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nodes'),
        ),
    ]
