# Generated by Django 3.0.8 on 2021-06-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210531_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='inputs',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='outputs',
            new_name='output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='proccessor',
        ),
        migrations.AddField(
            model_name='problem',
            name='proccessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nodes'),
        ),
    ]
