# Generated by Django 3.0.8 on 2021-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210602_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_tag',
            field=models.CharField(max_length=200),
        ),
    ]
