# Generated by Django 3.0.8 on 2021-06-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210602_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_tag',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
