# Generated by Django 3.0.8 on 2021-06-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210602_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputs',
            name='node',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='proccessor',
        ),
        migrations.AddField(
            model_name='outputs',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input',
        ),
        migrations.AddField(
            model_name='problem',
            name='input',
            field=models.ManyToManyField(through='api.outputs', to='api.inputs'),
        ),
    ]
