# Generated by Django 3.0.8 on 2021-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210607_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='final_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
