# Generated by Django 3.0.8 on 2021-06-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_problem_final_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='input',
            field=models.CharField(max_length=200),
        ),
    ]
