# Generated by Django 3.0.8 on 2021-06-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210608_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='final_answer',
            field=models.CharField(default='not computed', max_length=200),
        ),
    ]
