# Generated by Django 3.0.8 on 2021-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210608_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_tag',
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
