# Generated by Django 3.0.8 on 2021-06-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210608_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputs',
            name='tt',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
