# Generated by Django 3.0.8 on 2021-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_inputs_tt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputs',
            name='output',
            field=models.CharField(max_length=200),
        ),
    ]
