# Generated by Django 3.0.8 on 2021-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210608_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputs',
            name='output',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
