# Generated by Django 3.0.8 on 2021-07-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210608_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='tt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
