# Generated by Django 3.0.8 on 2021-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210715_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='tt',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
